name: Deploy Frontend Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: docker build -t zachsham/noted-sales-crm-frontend:latest -f client/Dockerfile client
      - name: Publish Image to docker hub
        run: docker push zachsham/noted-sales-crm-frontend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull zachsham/noted-sales-crm-frontend:latest 
      - name: Delete old container
        run: docker rm -f noted-salescrm-frontend-container || true
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name noted-salescrm-frontend-container zachsham/noted-sales-crm-frontend:latest
